### ISSUE TITLE
assign_sstate! & islog

### ISSUE THREAD

**Issue by Nic2020** [bankofcanada/ModelBaseEcon.jl#28]
The function assign_sstate! does not seem to be able to handle log variables by setting all the slopes to 0 if they are not provided.
See below.
![log_slope](https://user-images.githubusercontent.com/30166151/193629804-621bb5c5-1288-4a8e-a862-f52fe245775c.png)

**Comment by bbejanov** [comment]
Fix is in the dev branch in PR #27
