### ISSUE TITLE
Consider a different strategy of looking up the index for an equation

### ISSUE THREAD

**Issue by KristofferC** [bankofcanada/ModelBaseEcon.jl#44]
As shown in https://github.com/bankofcanada/ModelBaseEcon.jl/pull/41 and https://github.com/bankofcanada/StateSpaceEcon.jl/pull/39 it is currently very easy to hit a bottleneck by calling the `_index_of_var` function in e.g. a loop.

Instead, I think would perhaps be useful to cache the eq -> index lookup in the model. This requires keeping this cache up to date if e.g. equations are added and removed but it should not be too difficult.

**Comment by bbejanov** [comment]
Thanks for the suggestion. 
Done in commit d9cdc09676270d8259ef99bcb3da58d9a1b565e2 in #35
