### ISSUE TITLE
Deepcopy() breaks linearize!()

### ISSUE THREAD

**Issue by Nic2020** [bankofcanada/ModelBaseEcon.jl#60]
linearize! doesn't work after deepcopy and assign_sstate

`m = deepcopy(m_original)`
`assign_sstate!(m, init)`
`linearize!(m)`
`solve!(m, solver=:firstorder)`
`pl  = Plan(m, 2000Q1:2049Q4)`
`data_j  = steadystatedata(m,pl)`
`data_j.lc_shk[2000Q1] = 0.05`
`data_sim  = simulate(m,pl,data_ss; anticipate = false, verbose = true, solver = :firstorder)`

**Comment by bbejanov** [comment]
I run the same code and everything seems fine. What do you mean by "linearize! doesn't work" - are you getting an error message?

**Comment by Nic2020** [comment]
I can't replicate the issue anymore. I'll close it.

![issue60](https://github.com/bankofcanada/ModelBaseEcon.jl/assets/30166151/195ec913-71e9-4249-b64f-afcd5b514f90)
